#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(){
    FILE* tfile;
	tfile = fopen("/home/safidison/Mit/login/conn.csv", "r");
    char ch[255];
    char loha[1000];
	fgets(ch,255,tfile);
    (strcmp(ch,"none")==0)?strcpy(loha,"<meta http-equiv='refresh' content='2;url=http://www.login.mg/'>"):strcpy(loha,"");
    printf("Content-type:text/html\n\n");
    printf("<!DOCTYPE html>"
        "<html lang=\"en\">"
        "<head>"
            "<meta charset=\"UTF-8\">"
            "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
            "%s"
            "<title>User</title>"
            "<style>"
                "body{"
                    "width: 99vw;"
                    "height: 98vh;"
                    "background: linear-gradient(20deg, #000, #151516, #333b35, #000);"
                    "display: flex;"
                    "justify-content: center;"
                    "align-items: center;"
                "}"
                "nav{"
                    "position: fixed;"
                    "top: 0vw;left: 0vw;"
                    "width: 100vw;"
                    "height: 5vw;"
                    "border-radius: .5vw;"
                    "font-family: cursive;"
                    "height: 2vw;"
                    "display: flex;"
                    "color: #fff;"
                "}"
                "nav h1{"
                    "font-size: 2vw;"
                    "margin: 1vw 0vw 0vw 2vw;"
                "}"
                "nav .icon{"
                    "background-image: url(http://www.login.mg/index.png);"
                    "background-size: cover;"
                    "background-position: center;"
                    "width: 4.5vw;"
                    "height: 4vw;"
                    "border-radius: 50%%;"
                "}"
                "nav #icon{"
                    "display: flex;"
                    "width: 10vw;"
                "}"
                "nav a{"
                    "margin: 1vw 1vw 0vw 82vw;"
                    "font-size: 1.5vw;"
                    "text-decoration: none;"
                    "font-family: serif;"
                "}"
                ".main{"
                    "display: flex;"
                "}"
                ".main .hd{"
                    "color: #fff;"
                    "margin-right: 5vw;"
                    "font-family: cursive;"
                    "font-size: 2vw;"
                    "padding: 4.5vw"
                "}"
                "form{"
                    "width: 50vw;"
                    "height: 20vw;"
                    "border-radius: .2vw;"
                    "display: flex;"
                    "justify-content: center;"
                    "align-items: center;"
                    "flex-direction: column;"
                    "font-size: 1vw;"
                    "text-align: center;"
                "}"
                ".in{"
                    "background-color: #131010;"
                    "font-family: serif;"
                    "width: 40vw;"
                    "height: 2vw;"
                    "margin: 1vw;"
                    "border-radius: 5vw;"
                    "font-size: 1.5vw;"
                    "padding: .5vw 2vw;"
                    "border: none;"
                    "color: #fff;"
                "}"
                ".btn{"
                    "margin: 3vw 0vw 6vw 0vw;"
                    "width: 44vw;"
                    "height: 3vw;"
                    "background: linear-gradient(3deg, #000, #460833, #f00, #f00, #f00);"
                "}"
            "</style>"
        "</head>"
        "<body>"
            "<nav>"
                "<div id=\"icon\">"
                    "<div class=\"icon\"></div>"
                    "<h1>%s</h1>"
                "</div>"
                "<a class=\"bt\" href=\"http://www.login.mg/cgi-bin/logout.cgi\">Logout</a>"
            "</nav>"
            "<div class=\"main\">"
                "<div class=\"hd\">"
                    "<p>Ce plateforme permet de chercher les informations d'authentification correspondantes avec l'utilisateur</p>"
                "</div>"
                "<form action=\"auth.cgi\" method=\"get\">"
                    "<input class=\"in\" type=\"text\" placeholder=\"Taper le nom d'utilisateur\" name=\"utilisateur\">"
                    "<input type=\"text\" value=\"1\" name=\"p\" style=\"display: none;\">"
                    "<input class=\"in btn\" type=\"submit\" value=\"Chercher\">"
                "</form>"
            "</div>"
        "</body>"
        "</html>", loha, ch);
    return 0;
}
